# Generated by Django 3.1.2 on 2021-01-10 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201209_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instagram',
            new_name='instagram_url',
        ),
    ]
